[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.envs.default]
path = ".envs/python/.venv"
python = "3.11.14"

[project]
name = "project-root"
version = "0.1.0"
requires-python = ">=3.11,<3.12"