name: s2n CI/CD Pipeline

# push: main으로 push -> CI 실행
# pull_request -> CI 실행
# release: PyPI 배포 실행
on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [published]

    # 코드 체크아웃, python 3.11 세팅, pytest 실행
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - name: Install test dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest test -v || echo "No tests found, skipping"

  build-package:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install packaging tools
        run: |
          pip install --upgrade build

      - name: Build Package
        run: |
          python -m build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: s2n-dist
          path: dist/

  deploy:
      needs: build-package
      if: github.event_name == 'release' && github.event.action == 'published'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11

        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: s2n-dist
            path: dist/

        - name: Install Twine
          run: |
            pip install --upgrade twine

        - name: Publish to PyPI
          env:
            TWINE_USERNAME: ${{ secrets.PYPI_USER }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
          run: |
            twine upload dist/* --non-interactive || echo "Deployment skipped"
  docker-deploy:  
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEV_PKG_TOKEN }}

      # 1. 도커 이미지 빌드 2. ghcr에 등록 ghcr.io/<owner>/s2n-docker:latest
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v4
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/s2n-docker:latest



